#!/command/with-contenv sh

exec s6-setuidgid appuser /opt/AdGuardHome/AdGuardHome \
                                             --no-check-update \
                                             -c /opt/AdGuardHome/conf/AdGuardHome.yaml \
                                             -w /opt/AdGuardHome/work
